export default [
    {
        id: "1",
        title: 'Jungle Cuise 2',
        genre: 'Adventure',
        description: 'Dreaming about saving countless lives and having another adventure, the feisty English feminist and doctor of botany, Dr Lily Houghton, embarks on a peril-laden mission to change the world. Along with her fashionable brother, MacGregor, Dr Houghton enlists the help of the arrogant, wisecracking riverboat skipper, Captain Frank Wolff, to guide them through the serpentine Amazon River in La Quila, his swift wooden boat. Now, as the intrepid trio ventures deeper and deeper into the heart of an impenetrable green maze, searching for something that cannot be found, a centuries-old curse and the ruthless aristocrat, Prince Joachim, threaten to put an end to their ambitious plans.',
        imageUrl: '/static/img/jungle-cruise.jpeg',
        director: 'Jaume Collet-Serra',
        year: '2021',
        rating: 6.6,
        category: 'Movie',
    },
    {
        id: "2",
        title: 'Man of Steel',
        genre: 'Superhero',
        description: 'An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened when other survivors of his home planet invade Earth.',
        imageUrl: '/static/img/man-of-steel.jpg',
        director: 'Zack Snyder',
        year: '2013',
        rating: 7.1,
        category: 'Movie',
    },
    {
        id: "6b3677b9-2798-4a60-95b9-966fdfe68e81",
        title: 'Avengers: Endgame',
        genre: 'Superhero',
        description: 'An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened when other survivors of his home planet invade Earth.',
        imageUrl: '/static/img/endgame.jpg',
        director: 'Anthony',
        year: '2019',
        rating: 8.4,
        category: 'Movie',
    },
] 